DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(250) NOT NULL,
	type VARCHAR(250) NOT NULL,
	place VARCHAR(250) NOT NULL,
	warranty INT NOT NULL
);